"""Add daily_tasks table

Revision ID: 1a92ca3c4919
Revises: 67dbb635f1d2
Create Date: 2025-04-29 13:18:25.629646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a92ca3c4919'
down_revision: Union[str, None] = '67dbb635f1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('card_id', sa.Integer(), nullable=False),
        sa.Column('section_id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('learning_path_id', sa.Integer(), nullable=False),
        sa.Column('scheduled_date', sa.Date(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=True),
        sa.Column('end_time', sa.Time(), nullable=True),
        sa.Column('status', sa.Enum('todo', 'done', 'skipped', name='dailytaskstatusenum'), nullable=False),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
        sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
        sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_tasks_card_id'), 'daily_tasks', ['card_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_course_id'), 'daily_tasks', ['course_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_id'), 'daily_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_learning_path_id'), 'daily_tasks', ['learning_path_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_scheduled_date'), 'daily_tasks', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_daily_tasks_section_id'), 'daily_tasks', ['section_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_status'), 'daily_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_daily_tasks_user_id'), 'daily_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_tasks_user_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_status'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_section_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_scheduled_date'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_learning_path_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_course_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_card_id'), table_name='daily_tasks')
    op.drop_table('daily_tasks')
    # ### end Alembic commands ###
