"""Add ended_at to user_tasks table

Revision ID: 4efe243b309e
Revises: 77870b72c43b
Create Date: 2025-04-19 17:51:05.901475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import mysql # Import only if needed for specific types

# revision identifiers, used by Alembic.
revision: str = '4efe243b309e'
down_revision: Union[str, None] = '77870b72c43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - ADJUSTED ###
    # This migration should ONLY add the 'ended_at' column.
    # Ensure previous incorrect operations (like drop_table) are removed.
    op.add_column('user_tasks', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - ADJUSTED ###
    # This migration's downgrade should ONLY drop the 'ended_at' column.
    # Ensure previous incorrect operations (like create_table) are removed.
    op.drop_column('user_tasks', 'ended_at')
    # ### end Alembic commands ###
