"""Fix DailyTask foreign key relationship definition (no schema change needed)

Revision ID: 84892dac8fbc
Revises: 1a92ca3c4919
Create Date: 2025-04-29 13:29:57.729642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84892dac8fbc'
down_revision: Union[str, None] = '1a92ca3c4919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. No changes needed as schema was correct, only model definition was fixed."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No database schema changes are required for this revision.
    # The fix was applied to the SQLAlchemy model definition in app/tasks/models.py.
    # The previous migration 1a92ca3c4919 already created the FK correctly.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema. No changes needed."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No database schema changes were made in the upgrade function.
    pass
    # ### end Alembic commands ###
