# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - zero-ai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_281C46DF6C5747049FCBDF4319C4F194 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A0C41F146B54830AEE9E6171D5DDFCB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_79EF2DC70D4A4D2296792234BF797A2B }}

      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'zero-ai'
          app-settings-json: |
            [
              {
                "name": "DB_PASSWORD",
                "value": "${{ secrets.DB_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "DB_HOST",
                "value": "${{ secrets.DB_HOST }}",
                "slotSetting": false
              },
              {
                "name": "DB_PORT",
                "value": "${{ secrets.DB_PORT }}",
                "slotSetting": false
              },
              {
                "name": "DB_USER",
                "value": "${{ secrets.DB_USER }}",
                "slotSetting": false
              },
              {
                "name": "DB_NAME",
                "value": "zero-ai-database",
                "slotSetting": false
              },
              {
                "name": "AZURE_OPENAI_API_KEY",
                "value": "${{ secrets.AZURE_OPENAI_API_KEY }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_OPENAI_ENDPOINT",
                "value": "${{ vars.AZURE_OPENAI_ENDPOINT }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_OPENAI_API_VERSION",
                "value": "${{ vars.AZURE_OPENAI_API_VERSION }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_OPENAI_DEPLOYMENT_NAME",
                "value": "${{ vars.AZURE_OPENAI_DEPLOYMENT_NAME }}",
                "slotSetting": false
              },
              {
                "name": "HOST",
                "value": "${{ vars.HOST }}",
                "slotSetting": false
              },
              {
                "name": "PORT",
                "value": "${{ vars.PORT }}",
                "slotSetting": false
              },
              {
                "name": "DEBUG",
                "value": "${{ vars.DEBUG }}",
                "slotSetting": false
              },
              {
                "name": "SSL_CA",
                "value": "DigiCertGlobalRootCA.crt.pem",
                "slotSetting": false
              }
            ]
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'zero-ai'
          slot-name: 'Production'
          package: release.zip
          
      - name: Verify deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          response=$(curl -s -o /dev/null -w "%{http_code}" https://zero-ai.azurewebsites.net/api/public-test)
          if [ "$response" != "200" ]; then
            echo "Deployment verification failed with status code: $response"
            exit 1
          fi
          echo "Deployment verified successfully!"
          